In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from keras.layers import *
from keras.models import *
from keras.utils import *
from sklearn.preprocessing import *
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import random
import re

Using TensorFlow backend.


In [2]:
file = './data/text.txt'
with open(file) as f:
    lines = f.readlines()
    for i in lines:
        print(i)

    _____ _   _ _____   _          ____ _____   _____ _____   _   _ ____

   |_   _| | | |  ___| | |    /¯\ |  __|_   _| |     |  ___| | | | |  __|

     | | | |_| | |_    | |   /   \| |__  | |   | (¯) | |_    | | | | |__

     | | |  _  |  _|   | |  ( (¯) )__  | | |   | | | |  _|   | | | |__  |

     | | | | | | |___  | |__|  ¯  |__| | | |   | (_) | |     | |_| |__| |

     |_| |_| |_|_____| |____|_|¯|_|____| |_|   |_____|_|     |_____|____|

 Game Script by Shotgunnova (P. Summers) / Email: shotgunnova(a+)gmail(d0t)com





   01) Prologue - Hometown ............................................. GS01

   02) Summer - The Quarantine Zone .................................... GS02

   03) Summer - The Outskirts .......................................... GS03

   04) Summer - Bill's Town ............................................ GS04

   05) Summer - Pittsburgh ............................................. GS05

   06) Summer - The Suburbs ............................................ 



Joel: Just gimme a minute.



[He uses a dumpster as a makeshift stepping stone.]



Ellie: This tunnel...you use it to smuggle things?



Joel: Yep.



Ellie: Like illegal things?



Joel: Sometimes.



Ellie: You ever smuggle a kid before?



Joel: No. That's a first. So what's the deal with you and Marlene, anyways?



Ellie: I don't know. She's my friend, I guess.



Joel: Your friend, huh? You're friends with the leader of the Fireflies.

      What're you, like twelve?



Ellie: She knew my mom, and she's been looking after me. And I'm fourteen, not

       that that has anything to do with anything.



Joel: So where are your parents?



Ellie: Where are anyone's parents? They've been gone a long, long time.



Joel: Hm. So instead of just staying in school, you decide to run off and join

      the Fireflies, is that it?



Ellie: Look, I'm not supposed to tell you why you're smuggling me, if that's

       what you're getting at.



Joel: You wanna know the best thing about 




[They can hear Tess fighting nearby.]



Ellie: Oh man...



Joel: Just keep pushing forward.



[From the balcony, they can see Tess' body.]



Ellie: Oh my god. Tess...



Guard: Target neutralized. She took out two of my men. Copy that. You, take

       out that door. You, with me.



Guard 2: Yes, sir.



Ellie: They're gonna be here soon.



[They continue their frantic escape into a new wing.]



Joel: We're through.



Ellie: What do we do? Joel?



Joel: I got this.



[He kills the squad and they move to the ground floor.]



Ellie: What're we doing? Joel, how're we gonna get outta here?



Joel: Alright. We're gonna have to go through that hall.



Guard: They had to come through here. Comb the area.



Joel: Stay down. I don't know how many more there are.



Guard: They still haven't found the last two.



Guard 2: I heard one of 'em was a kid.



Guard: Does it matter? They took out a bunch of our guys.



Guard 2: Jesus. Well hey, after today this whole Firefly bullsh

Bill: What, the doggy door?



Joel: Be very careful.



[He pries the planks off the lower flap.]



Ellie: Of course.



Bill: Maybe you should've given her a gun.



Joel: Okay, Bill.



[She unlocks the door.]



Ellie: There's more of those clicker things inside the house.



Bill: Oh, shit.



Joel: They ain't seen us yet. Just stay down.



Ellie: Careful.



[They make it through the house.]



Bill: Alright, c'mon, let's get up. On the RV and over. We should be clear.



[They cross a plank to a treehouse.]



Ellie: Who the hell left this here? You got friends in town?



Bill: No. Although I have some idea who mighta come through here. School's on

      the other side of this house. Let's get inside.



Joel: C'mon, Ellie. Alright, I think we're good.



Bill: For now. Goddamn those things. Nobody's bitten, right?



Ellie: Nope. I'm good.



Joel: We're all fine. Let's just keep going.



[They enter the house to explore. Joel and Ellie go upstairs.]



Ellie: Hey, you got

Joel: I'm alright! Are you okay?



Ellie: No! You scared the shit outta me! I'm...I'm gonna climb down there,

       okay?



Joel: No! Stay up there. I'll make my way up to you!



Ellie: Don't do anything stupid!



Joel: I'll try.



[He navigates the flooded B1 level.]



Joel: Maybe that way. That could be it.



[The door becomes blocked by debris.]



Joel: Goddamnit. I don't think I tried over there yet.



[He swims further.]



Joel: Over there. I need to find a way around this gate. Well, maybe that

      doorway. Oh, damn it. Spores.



[He hears a loud splashing sound nearby.]



Joel: Oh shit.



[He finds stalkers who alert the others nearby.]



Joel: I hate these things.



[Joel restarts a generator, which attracts more stalkers]



Joel: Goddammit!



[At a keycard door, Joel tries using the keycard he found.]



Joel: Made it. Ah, so much for that. I gotta find Ellie.



[In a restaurant kitchen, he finds more hunters killing a clicker]



Hunter: It's down. Fini



Henry: There'll come a day when kids can just be kids again.



Joel: Let's go.



[They find the far street blocked by debris. A Firefly symbol's nearby.]



Henry: Fireflies were here.



Joel: Yeah, by the looks of it.



Sam: How're we gonna find them?



Joel: I know a guy. My brother, actually. He was a Firefly. Last I heard he

      was in Wyoming. We get there, we find him. We find the Fireflies.

      Whaddya say, you in?



Henry: Sounds like a good plan, man.



Ellie: Ah, okay. You guys are killing me with your downer talk. It's joke

       book time.



Sam: What is that?



Ellie: Just bear with me. "You wanna hear a joke about pizza? Never mind, it

       was too cheesy."



Sam: I don't get it.



Ellie: Yeah, me neither. "What did the green grape say to purple grape?

       Breathe, you idiot!"



Sam: That's so stupid. Alright, I got a joke for you.



Ellie: Let's hear it.



Sam: Why can't your nose be twelve inches long?



Ellie: I don't know, why?



Sam: 


Ellie: You're not okay, Joel! Now come on! Move it. There's no one here. Hurry.



[He slowly follows her, about to double over any minute.]



Ellie: You're doing good, just keep at it.



Joel: I'm coming.



Ellie: Through these double doors. Oh man. Here, lean on me.



Joel: No.



Ellie: Well can you walk?



Joel: Yes.



Ellie: Then fucking walk. Come on. There's the exit. Just a little bit more,

       come on. Hey, hey! Joel!



Joel: Behind you!



Ellie: What?



Joel: Ellie!



Hunter: The kid's got a gun! Watch out! Hey!



Ellie: Stay the fuck back!



[She guns one down down.]



Ellie: Oh shit, oh shit.



Hunter 2: You little shit!



[He clubs her, but she still caps him.]



Ellie: Joel. Here, stand up. I swear to god, I get you out of this, you are so

       singing for me.



Joel: You wish.



Ellie: Wait here. I'll get the door.



Joel: Take your time.



Ellie: Come on. There you go.



[He makes it outside, but rolls down the steps near a hunter taking Cal

author (P. Summers). It cannot be hosted, edited, or distributed for profit,

and may not be given away as an add-in/gift to bought items. All rights are

reserved to respective parties, even those not explicitly stated herein. Those

who find this document on sites not listed below should e-mail the author (me).

Thanks for reading this, and thanks for respectin' FAQ authors.



 Allowed Sites:                       Disallowed Sites:



  • Gametalk.com                       • cheatcc.com

  • GameFAQs.com                       • gamershell.com

  • MyCheats.com

  • Neoseeker.com

  • Gamesradar.com

  • Supercheats.com

  • Cheathappens.com

  • Honestgamers.com

  • Chaptercheats.com                           E-mail me for permissions ~

  • Cavesofnarshe.com                        shotgunnova (a+) gmail (d0t) com.

_______________________________________________________________________________

TAKE MY                       Document © Shotgunnova, 1997-2014 (and countin'!)

MONEY,

In [3]:

text=''
with open(file) as f:
    lines = f.readlines()
    text = text.join([l for l in lines if re.match(r'^[A-Z].*:', l)])

text
    

'Joel: Tommy, I-...Tommy. Tommy, listen to me. He\'s the contractor, okay? I\nSarah: Hey.\nJoel: Scoot.\nSarah: Fun day at work, huh?\nJoel: What are you still doing up? It\'s late.\nSarah: Oh crud. What time is it?\nJoel: It\'s way past your bedtime.\nSarah: But it\'s still today.\nJoel: Honey, please not right now. I do not have the energy for this.\nSarah: Here.\nJoel: What\'s this?\nSarah: Your birthday.\nSarah: You kept complaining about your broken watch... So I figured, you know.\nJoel: Honey, this is...\nSarah: What?\nJoel: It\'s nice, but I-...I think it\'s stuck. It\'s not...\nSarah: What? No, no, no, no.\nSarah: Oh, ha, ha.\nJoel: Where did you get the money for this?\nSarah: Drugs. I sell hardcore drugs.\nJoel: Oh, good. You can start helping out with the mortgage then.\nSarah: Stsh - yeah, you wish.\nJoel: Goodnight, baby girl.\nSarah: Hello?\nTommy: Sarah, honey, I need you to get your daddy on the phone.\nSarah: Uncle Tommy, what time is it?\nTommy: I need to talk to you

In [4]:
array = []
for t in text.split('\n')[:1000]:
    array.append(t)

In [5]:
token = Tokenizer(lower=False, filters='.,?;"-_')
token.fit_on_texts(array)

In [6]:
token.word_index

{'Joel:': 1,
 'Tess:': 2,
 'the': 3,
 'I': 4,
 'you': 5,
 'Ellie:': 6,
 'to': 7,
 'it': 8,
 'a': 9,
 'this': 10,
 'we': 11,
 'You': 12,
 'Sarah:': 13,
 'of': 14,
 'here': 15,
 'up': 16,
 'out': 17,
 'that': 18,
 'on': 19,
 'get': 20,
 'is': 21,
 'are': 22,
 'me': 23,
 'Tommy:': 24,
 'your': 25,
 "I'm": 26,
 'What': 27,
 'do': 28,
 'in': 29,
 'go': 30,
 'Oh': 31,
 'for': 32,
 'just': 33,
 'Yeah': 34,
 'We': 35,
 "Let's": 36,
 'us': 37,
 'Marlene:': 38,
 'there': 39,
 'know': 40,
 'with': 41,
 'Guard:': 42,
 '2:': 43,
 'No': 44,
 'and': 45,
 'Tess': 46,
 "It's": 47,
 'was': 48,
 'gonna': 49,
 'Hey': 50,
 'not': 51,
 'be': 52,
 'way': 53,
 'what': 54,
 'back': 55,
 'they': 56,
 'Alright': 57,
 'Joel': 58,
 'got': 59,
 'see': 60,
 'around': 61,
 "don't": 62,
 'can': 63,
 'shit': 64,
 "C'mon": 65,
 'How': 66,
 'through': 67,
 'Okay': 68,
 'Look': 69,
 'This': 70,
 'have': 71,
 'all': 72,
 'Get': 73,
 'hell': 74,
 'Man:': 75,
 'my': 76,
 "'em": 77,
 'Well': 78,
 'our': 79,
 'now': 80,
 'need

In [7]:
len(token.word_index)

1439

In [8]:
sequence = token.texts_to_sequences(array)

In [9]:
sequence

[[1, 124, 4, 124, 124, 646, 7, 23, 168, 3, 647, 94, 4],
 [13, 50],
 [1, 648],
 [13, 649, 342, 102, 277, 343],
 [1, 27, 22, 5, 103, 199, 16, 47, 650],
 [13, 31, 651, 27, 135, 21, 8],
 [1, 47, 53, 447, 25, 652],
 [13, 231, 84, 103, 232],
 [1, 344, 448, 51, 85, 80, 4, 28, 51, 71, 3, 653, 32, 10],
 [13, 200],
 [1, 185, 10],
 [13, 345, 654],
 [13, 12, 655, 656, 88, 25, 346, 169, 136, 4, 657, 5, 40],
 [1, 344, 10, 21],
 [13, 27],
 [1, 47, 658, 170, 4, 4, 95, 84, 659, 47, 51],
 [13, 27, 44, 96, 96, 96],
 [13, 31, 449, 449],
 [1, 125, 137, 5, 20, 3, 660, 32, 10],
 [13, 661, 4, 450, 662, 663],
 [1, 31, 104, 12, 63, 664, 665, 17, 41, 3, 666, 233],
 [13, 667, 347, 5, 668],
 [1, 669, 105, 348],
 [13, 349],
 [24, 201, 451, 4, 81, 5, 7, 20, 25, 670, 19, 3, 452],
 [13, 278, 124, 54, 135, 21, 8],
 [24, 4, 81, 7, 350, 7, 25, 671, 80, 106, 158],
 [13, 278, 124, 349],
 [13, 27, 48, 18, 72, 88, 186, 234, 12, 29, 15],
 [279, 280, 672, 18, 54, 11, 673, 674, 281, 675, 676, 7, 52],
 [13, 125, 3, 677, 22, 5],


In [10]:
sequence = pad_sequences(sequence, maxlen=10)
sequence




array([[ 124,  124,  646, ...,  647,   94,    4],
       [   0,    0,    0, ...,    0,   13,   50],
       [   0,    0,    0, ...,    0,    1,  648],
       ...,
       [ 594,   49, 1437, ...,   16,   46,  434],
       [   0,    0,    0, ...,    0,    6,  341],
       [   0,    0,    0, ...,    1, 1439,    8]], dtype=int32)

In [11]:
X = sequence
Y = np.vstack((X[1:], X[0]))
Y

array([[   0,    0,    0, ...,    0,   13,   50],
       [   0,    0,    0, ...,    0,    1,  648],
       [   0,    0,    0, ...,  102,  277,  343],
       ...,
       [   0,    0,    0, ...,    0,    6,  341],
       [   0,    0,    0, ...,    1, 1439,    8],
       [ 124,  124,  646, ...,  647,   94,    4]], dtype=int32)

In [12]:
Y.shape

(1000, 10)

In [13]:
# reshape
X = X.reshape(-1, 10, 1)
Y = Y.reshape(-1, 10, 1)
X

array([[[ 124],
        [ 124],
        [ 646],
        ...,
        [ 647],
        [  94],
        [   4]],

       [[   0],
        [   0],
        [   0],
        ...,
        [   0],
        [  13],
        [  50]],

       [[   0],
        [   0],
        [   0],
        ...,
        [   0],
        [   1],
        [ 648]],

       ...,

       [[ 594],
        [  49],
        [1437],
        ...,
        [  16],
        [  46],
        [ 434]],

       [[   0],
        [   0],
        [   0],
        ...,
        [   0],
        [   6],
        [ 341]],

       [[   0],
        [   0],
        [   0],
        ...,
        [   1],
        [1439],
        [   8]]], dtype=int32)

In [14]:
Y = to_categorical(Y)
Y

array([[[1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [15]:
Y.shape

(1000, 10, 1440)

In [16]:
# modeling
model = Sequential()
model.add(Bidirectional(SimpleRNN(128, return_sequences=True), input_shape=(10,1)))
model.add(Bidirectional(SimpleRNN(128, return_sequences=True)))
model.add(Dense(1440, activation='softmax'))

In [17]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bidirectional_1 (Bidirection (None, 10, 256)           33280     
_________________________________________________________________
bidirectional_2 (Bidirection (None, 10, 256)           98560     
_________________________________________________________________
dense_1 (Dense)              (None, 10, 1440)          370080    
Total params: 501,920
Trainable params: 501,920
Non-trainable params: 0
_________________________________________________________________


In [18]:
# compile
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


In [19]:
# training
model.fit(X, Y, epochs=100, batch_size=1)

Epoch 1/100
1000/1000 [==============================] - 57s 57ms/step - loss: 5.0006 - acc: 0.3477
Epoch 2/100
1000/1000 [==============================] - 52s 52ms/step - loss: 4.6259 - acc: 0.3514
Epoch 3/100
1000/1000 [==============================] - 52s 52ms/step - loss: 4.4655 - acc: 0.3537
Epoch 4/100
1000/1000 [==============================] - 51s 51ms/step - loss: 4.3202 - acc: 0.3531
Epoch 5/100
1000/1000 [==============================] - 52s 52ms/step - loss: 4.1692 - acc: 0.3514
Epoch 6/100
1000/1000 [==============================] - 52s 52ms/step - loss: 4.0331 - acc: 0.3506
Epoch 7/100
1000/1000 [==============================] - 52s 52ms/step - loss: 3.9064 - acc: 0.3513
Epoch 8/100
1000/1000 [==============================] - 52s 52ms/step - loss: 3.7679 - acc: 0.3485
Epoch 9/100
1000/1000 [==============================] - 52s 52ms/step - loss: 3.6254 - acc: 0.3501
Epoch 10/100
1000/1000 [==============================] - 52s 52ms/step - loss: 3.4896 - acc: 0.3503

1000/1000 [==============================] - 48s 48ms/step - loss: 1.0572 - acc: 0.7063
Epoch 83/100
1000/1000 [==============================] - 48s 48ms/step - loss: 1.0280 - acc: 0.7166
Epoch 84/100
1000/1000 [==============================] - 47s 47ms/step - loss: 1.0155 - acc: 0.7195
Epoch 85/100
1000/1000 [==============================] - 47s 47ms/step - loss: 1.0461 - acc: 0.7143
Epoch 86/100
1000/1000 [==============================] - 48s 48ms/step - loss: 1.1144 - acc: 0.6876
Epoch 87/100
1000/1000 [==============================] - 47s 47ms/step - loss: 0.9962 - acc: 0.7185
Epoch 88/100
1000/1000 [==============================] - 47s 47ms/step - loss: 0.9886 - acc: 0.7286
Epoch 89/100
1000/1000 [==============================] - 48s 48ms/step - loss: 1.0760 - acc: 0.7003
Epoch 90/100
1000/1000 [==============================] - 48s 48ms/step - loss: 1.0179 - acc: 0.7168
Epoch 91/100
1000/1000 [==============================] - 47s 47ms/step - loss: 1.0311 - acc: 0.7037
Epo

In [20]:
# model save
model.save('./data/temp_model')


In [21]:
# load
model = load_model('./data/temp_model')

In [22]:
# prediction
pred = model.predict(X[:1])

pred


array([[[8.93800855e-01, 7.72242376e-04, 1.57676323e-03, ...,
         4.82789669e-16, 3.14516382e-12, 5.53057644e-09],
        [6.18585348e-01, 1.14886183e-03, 1.61644239e-05, ...,
         1.18582102e-10, 1.24358343e-10, 2.27197123e-08],
        [8.06360900e-01, 2.08205995e-04, 2.35938653e-03, ...,
         1.29063405e-12, 2.66635265e-13, 1.35686493e-08],
        ...,
        [6.05583072e-01, 4.74206492e-04, 1.15165873e-04, ...,
         1.39643885e-12, 1.24153587e-11, 1.32186715e-08],
        [9.86944069e-04, 2.98194081e-01, 8.17255210e-03, ...,
         9.77224524e-10, 4.44845983e-12, 1.18386856e-08],
        [6.17529349e-06, 2.27628756e-04, 4.75364708e-04, ...,
         7.44520602e-13, 1.15269018e-11, 2.64691913e-09]]], dtype=float32)

In [23]:
pred = np.argmax(pred, axis=2)
pred

array([[ 0,  0,  0,  0,  0,  0,  0,  0, 13, 50]])

In [24]:
pred

array([[ 0,  0,  0,  0,  0,  0,  0,  0, 13, 50]])

In [25]:
pred.shape

(1, 10)

In [26]:
idx_word = {}
for w in token.word_index:
    idx_word[token.word_index[w]] = w
idx_word

{1: 'Joel:',
 2: 'Tess:',
 3: 'the',
 4: 'I',
 5: 'you',
 6: 'Ellie:',
 7: 'to',
 8: 'it',
 9: 'a',
 10: 'this',
 11: 'we',
 12: 'You',
 13: 'Sarah:',
 14: 'of',
 15: 'here',
 16: 'up',
 17: 'out',
 18: 'that',
 19: 'on',
 20: 'get',
 21: 'is',
 22: 'are',
 23: 'me',
 24: 'Tommy:',
 25: 'your',
 26: "I'm",
 27: 'What',
 28: 'do',
 29: 'in',
 30: 'go',
 31: 'Oh',
 32: 'for',
 33: 'just',
 34: 'Yeah',
 35: 'We',
 36: "Let's",
 37: 'us',
 38: 'Marlene:',
 39: 'there',
 40: 'know',
 41: 'with',
 42: 'Guard:',
 43: '2:',
 44: 'No',
 45: 'and',
 46: 'Tess',
 47: "It's",
 48: 'was',
 49: 'gonna',
 50: 'Hey',
 51: 'not',
 52: 'be',
 53: 'way',
 54: 'what',
 55: 'back',
 56: 'they',
 57: 'Alright',
 58: 'Joel',
 59: 'got',
 60: 'see',
 61: 'around',
 62: "don't",
 63: 'can',
 64: 'shit',
 65: "C'mon",
 66: 'How',
 67: 'through',
 68: 'Okay',
 69: 'Look',
 70: 'This',
 71: 'have',
 72: 'all',
 73: 'Get',
 74: 'hell',
 75: 'Man:',
 76: 'my',
 77: "'em",
 78: 'Well',
 79: 'our',
 80: 'now',
 81: '

In [27]:
for l in pred:
    for w in l:
        print(w)

0
0
0
0
0
0
0
0
13
50


In [28]:
temp=''
for l in pred:
    for w in l:
        if w != 0:
            temp += idx_word[w]
            temp += ' '
temp

'Sarah: Hey '

In [30]:
for i in range(10):
    temp=''
    ran = random.randrange(0, len(X))
    pred = model.predict(np.expand_dims(X[ran], axis=0))
    
    pred = np.argmax(pred, axis=2)
    for l in pred:
        for w in l:
            if w != 0:
                temp += idx_word[w]
                temp += ' '
        temp += '\n'
        
    print(array[ran])
    print(temp)
    

Joel: Good.
This He's dead! 

Sarah: Dad?
keep we're your c'mere 

Sarah: What? No, no, no, no.
Sarah: Oh ha ha 

Ellie: Oh, shit.
Tess here! RUN! 

Tess: C'mon, Ellie.
I'm alive Get look Okay 

Goon 3: I'm gonna fuckin' kill you!
I'll cover you Get the angle that them 

Ellie: Like bats.
clicking hide That's how they 

Joel: No, no, no, that was your crusade. I am not doin' that.
there's enough here that you have to feel some sort 

Soldier: Stop right there!
Joel: we're I sick 

Guard 2: Fuckin' shoot 'em!
They're running! Call for backup! 

